### ISSUE TITLE
question about the inference speed

### ISSUE THREAD

**Issue by yifanzhang713** [AndyYuan96/HVNet#2]
Hi, I finished the model training but failed to get the similar speed result according to paper. 
about 20 FPS on a RTX2080ti while the official result is 31 FPS. Do you know why this is?

**Comment by AndyYuan96** [comment]
> Hi, I finished the model training but failed to get the similar speed result according to paper.
> about 20 FPS on a RTX2080ti while the official result is 31 FPS. Do you know why this is?

The training code should have some space to optimize, such as generating input different scale feature(for input scale and output scale, even the scale is same, I generate two times, for example, for input scale(0.5,1,2), and output scale(1,2,4), I generate twice for 1 and 2 in input scale and scale, you can just generate one time for 1 and 2), and the training code is writen to satisfy easy to configure different options. What's more, you can use tensorrt to accelation, the paper don't say their run code in python.

**Comment by yifanzhang713** [comment]
Thank you very much for your reply and the aviliable code, I will try to take a look at it carefully.
